# Streamlit Secrets 설정 파일
# 이 파일을 .streamlit/secrets.toml 경로에 저장하세요

# HyperCLOVA X API 키
CLOVA_STUDIO_API_KEY = "nv-2ed80b2afdba4fee87ca1139c4c5271bR5JQ"

# 선택사항: 다른 API 키들
# OPENAI_API_KEY = "your-openai-key"
# YAHOO_FINANCE_API_KEY = "your-yahoo-finance-key"

# 데이터베이스 설정 (필요시)
# [database]
# host = "localhost"
# port = 5432
# username = "your-username"
# password = "your-password"
# database = "investment_db"
